version: "3"

services:
  gateway:
    container_name: gateway
    restart: always
    build: ./gateway
    ports:
      - "8000:8000"

  characters:
    container_name: characters
    restart: always
    build: ./characters
    ports:
      - ":8001"

  films:
    container_name: films
    restart: always
    build: ./films
    ports:
      - ":8002"

  planets:
    container_name: planets
    restart: always
    build: ./planets
    ports:
      - ":8003"

  database:
    container_name: database
    restart: always
    build: ./database
    ports:
      - ":8004"
    env_file:
      - .env

  registers:
    container_name: registers
    restart: always
    build: ./registers
    ports:
      - ":8005"
    env_file:
      - .env

  login:
    container_name: login
    restart: always
    build: ./login
    ports:
      - ":8006"
    env_file:
      - .env

  logout:
    container_name: logout
    restart: always
    build: ./logout
    ports:
      - ":8007"
